[project]
org-name = "ballerina"
version = "0.6.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "socket"
    version = "1.3.0-SNAPSHOT"
    path = "../socket-utils/build/libs/socket-utils-1.3.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["socket"]
